### PR TITLE
Create a phar package with Box

### PR DESCRIPTION
**Pull request by srosato**
This pull request adds the possibility to create a Phar archive using Box.

### CODE REVIEW

**Comment by srosato** [comment]
I have also included the built phar package in the commit using the latest revision.

**Comment by igorw** [comment]
Can you please remove the compiled phar from the repo? I don't really want to have to re-build it on every commit.

**Comment by srosato** [comment]
Here you go

**Comment by igorw** [comment]
Merged, thanks!

**Pull request merged**
