### PR TITLE
Make converter a normal app using Symfony's Console component

### PR DESCRIPTION
**Pull request by olegstepura**
here is my 50 cents to make this tool a standalone application

### CODE REVIEW

**Comment by olegstepura** [comment]
I'm closing this as I gonna make this a little bit more general tool and it seems like you won't merge.

**Comment by igorw** [comment]
I definitely was planning to merge it. There were some parts I did not like (over-complicated imo), but did not get round to it yet. Feel free to re-open or submit a new PR.

**Comment by olegstepura** [comment]
Well, actually I'm going to rename the app itself and support php and xml coonfiguration format aswell.

**Comment by igorw** [comment]
What ever happened to keeping it simple? Well, as you wish. ;-)

**Comment by olegstepura** [comment]
Well, I was thinking about renaming it so that the name would tell others that it's not only for composer. It may be used to convert any other configuration file. For example I may wish to write DI configuration myself as a yaml file but convert it to xml for distribution.
And so the name should be something like `convert-config`. What do you think about the new name?
I don't mind merging it again after refactoring if you don't mind changing the name to something more general.

**Comment by igorw** [comment]
Honestly, I'm not not really interested in such a tool. There are some technical implications (there is no generic way to serialize to XML), but the main point is that I want to invest time in things that make a difference.

I wrote this tool because people are wasting time arguing about composer not supporting YAML. I probably won't use it, but if other people do use it, that will let everyone focus on solving more important problems.

This is simply my view. If you find it interesting, challenging or useful to write a very generic tool that can convert any kind of configuration from any format to any other format, do it. ;-)

**Comment by igorw** [comment]
At this point it's just way over-engineered imo. I will work on making composer-yaml more robust and _maybe_ using the console component, but I don't want to create a general purpose config conversion tool. So I will close this.

**Comment by igorw** [comment]
FYI, pushed an updated version which uses console.

**Comment by olegstepura** [comment]
Duplicated efforts, but as you like. =) Hopefully one day composer would not need such a tool starting to support yaml configuration files as well.

**Pull request closed without merging**
